### ISSUE TITLE
Element: classes manipulated with renderer in `created` get overwritten

### ISSUE THREAD

**Issue by kvcrawford** [kriszyp/alkali#23] opened 2016-09-23 17:34 UTC
```js
class Foo extends Div('.foo') {
  // @param { Variable.<Boolean>} active
  created({active}) {
    new ElementRenderer({
      element: this,
      variable: active,
      renderUpdate: (isActive) => {
        this.classList.toggle('active', isActive)
        this.classList.toggle('inactive', !isActive)
        this.classList.toggle('hidden', !isActive)
      }
    })
  }
}
```

```js
new Foo({ active: new Variable(false) })
```

Results in 

```html
<div class="foo"></div>
```

Expected
 
```html
<div class="foo hidden inactive"></div>
```

**Comment by kriszyp** [comment] 2016-09-23 19:43
@kvcrawford , I think this is because `created` executes *before* properties are assigned to, so you are setting the element `class` (vicariously through `classList`), but then that is overriden by the property assignment that happens after `created`. `created` runs at this time by design. A few options:
1. Use `classes` (the preferred approach for toggling classes):
```
import { not, Div} from 'alkali'
class Foo extends Div('.foo') {
  created(properties) {
    let {active} = properties
    properties.classes = {
      active: active,
      inactive: not(active),
      hidden: not(active)
    }
  }
```
2. Simple change the `created` to `ready` (`ready` runs after the properties are assigned).
3. It would be possible to change the assignment code for `className` to check if there was an existing value. I think I would prefer to avoid the extra property check from a performance perspective, but perhaps this isn't an unreasonable request.

**Closed** 2016-10-18 20:36 UTC
